version: '2'
services:
# service configuration for our dockerized Rails app
  db:
    image: postgres:9.4.5
    # volumes:
    #   - /tmp:/var/lib/postgresql/data
  app:
    build: .
    env_file: .env
    environment:
      RAILS_ENV: $RAILS_ENV
    depends_on:
      - db
    expose:
      - "3000"
  web:
    build:
      context: config/containers
      dockerfile: Dockerfile-nginx
    depends_on:
      - app
    ports:
      - "80:80"
