version: '2'
services:
# service configuration for our dockerized Rails app
  db:
    image: postgres:9.4.5
    volumes:
      - "/tmp/alpha_blog:/var/lib/postgresql/data"
  app:
    build: .
    env_file: .env
    environment:
      RAILS_ENV: $RAILS_ENV
    depends_on:
      - db
    ports:
      - "3000:3000"
  # web:
  #   build: app/.
  #     # context: config/containers
  #     # dockerfile: Dockerfile-nginx
  #   depends_on:
  #     - app
  #   ports:
  #     - "80:80"
