default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  port: 5432
  username: postgres
  password: <%= ENV['POSTGRES_PASSWORD'] %>

development:
  <<: *default
  database: alpha_dev #CHANGE ME

test:
  <<: *default
  database: alpha_test #CHANGE ME

production:
  <<: *default
  database: alpha_prod #CHANGE ME
